config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :appointments
  resources :physicians

  get "Pacientes", to: 'patients#index'
  get "Medicos", to: 'physicians#index'
  get "Consultas", to: 'appointments#index'
  get "Home", to: 'home#index'
  get "Relatorio", to: 'patients#show'
  

  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient

  accepts_nested_attributes_for :patient, reject_if: :all_blank, allow_destroy: true

end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :physicians, through: :appointments

end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments

    accepts_nested_attributes_for :appointments, :reject_if => :all_blank, allow_destroy: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:physician_id, :patient_id, :appointment_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    @physicians = Physician.all
    @patients = Physician.all
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :email, :descricao, :_destroy, :id)
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @physicians = Physician.all
    @patients = Physician.all
  end

  # GET /physicians/1 or /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
    @patients = @physician.patients.build
    @appointments = @physician.appointments.build
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully created." }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully updated." }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url, notice: "Physician was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
      params.require(:physician).permit(:name, :tipo, :descricao, :appointments_attributes => [:id, :appointment_date, :physician_id, :patient_id, :_destroy, :patient_attributes => [:id, :name]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :physician_id %>
    <%= form.text_field :physician_id%>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.text_field :patient_id %>
  </div>

  <div class="field">
    <%= form.label :appointment_date %>
    <%= form.datetime_select :appointment_date %>
  </div>

  <div class="field">
    <%= form.label :descricao_paciente %>
    <%= form.text_area :descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<body style="background-color: #A5DAE0;">
<%= link_to 'New Appointment', new_appointment_path %>


    <div class="row">
      <div class="col-xs-6">
        <h3 class="panel-title text-center">Consultas</h3>
          
        
      </div>
    </div>
   
    <hr style="background-color: black
    ;">

<% @appointments.each do |appointment| %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<div class="section_our_solution" style="align-items: flex-start !important;">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="our_solution_category" style="width: 40%;">
        <div class="solution_cards_box">
          <div class="solution_card">
            <div class="hover_color_bubble"></div>
            <div class="so_top_icon">
              <svg id="Layer_1" enable-background="new 0 0 512 512" height="50" viewBox="0 0 512 512" width="40" xmlns="http://www.w3.org/2000/svg">
                <g>
                  <g>
                    <g>
                      <g>
                        <path d="m47.478 452.317 295.441 19.76c5.511.369 10.277-3.8 10.645-9.31l28.393-424.517c.369-5.511-3.8-10.276-9.31-10.645l-295.441-19.76c-5.511-.369-10.276 3.8-10.645 9.31l-28.394 424.517c-.368 5.511 3.8 10.277 9.311 10.645z" fill="#fae19e" />
                      </g>
                      <g>
                        <g>
                          <g>
                            <g>
                              <g>
                                <path d="m17.5 504.177h226.14l79.96-79.605v-355.86c0-5.523-4.477-10-10-10h-296.1c-5.523 0-10 4.477-10 10v425.466c0 5.522 4.477 9.999 10 9.999z" fill="#fff9e9" />
                              </g>
                              <path d="m313.601 58.712h-40c5.523 0 10 4.477 10 10v355.861l-.258 40.078 40.258-40.078v-355.861c0-5.523-4.477-10-10-10z" fill="#fff4d6" />
                            </g>
                          </g>
                        </g>
                        <path d="m243.64 504.177v-70.253c0-5.523 4.477-10 10-10h69.96z" fill="#ffeec2" />
                      </g>
                    </g>
                    <g>
                      <path d="m468.636 248.58-33.372.165v-50.826c0-9.183 7.463-16.662 16.673-16.708h.007c9.217-.046 16.693 7.371 16.693 16.562v50.807z" fill="#fed23a" />
                      <path d="m451.96 504.177c-10.362-10.277-16.196-24.263-16.208-38.857l-.062-73.973c0-.644.524-1.169 1.171-1.173l30.038-.149c.647-.003 1.171.517 1.171 1.161l.062 74.079c.012 14.531-5.749 28.472-16.015 38.756z" fill="#54b1ff" />
                      <path d="m451.959 469.333h-.01c-14.434.072-26.14-11.542-26.14-25.935v-213.527c0-6.778 5.477-12.283 12.255-12.316l27.626-.137c6.826-.034 12.378 5.49 12.378 12.316v213.436c0 14.38-11.687 26.091-26.109 26.163z" fill="#fdf385" />
                      <path d="m465.69 217.417-23.769.118c6.037.79 10.708 5.94 10.708 12.198v213.437c0 9.823-5.455 18.397-13.507 22.87 3.79 2.115 8.164 3.317 12.826 3.293h.01c14.422-.072 26.109-11.783 26.109-26.163v-213.436c.001-6.826-5.551-12.351-12.377-12.317z" fill="#faee6e" />
                      <path d="m491.274 247.925-71.615.355c-7.305.036-13.226 5.968-13.226 13.248 0 7.281 5.921 13.153 13.226 13.117l58.389-.29v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c0-7.28-5.922-13.152-13.226-13.116z" fill="#54b1ff" />
                      <g>
                        <path d="m491.274 247.925-38.441.188-.167 26.311 25.381-.067v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c.001-7.282-5.921-13.154-13.225-13.118z" fill="#3da7ff" />
                      </g>
                    </g>
                  </g>
                  <g fill="#060606">
                    <path d="m373.147 20.122-295.44-19.761c-9.631-.638-17.984 6.665-18.629 16.293l-2.311 34.557h-39.267c-9.649 0-17.5 7.851-17.5 17.5v425.466c0 9.649 7.851 17.5 17.5 17.5h226.141c1.96 0 3.902-.801 5.292-2.185l34.138-33.987c.347.074.701.133 1.065.157l58.282 3.898c9.302.614 18.005-6.952 18.629-16.293l28.393-424.515c.639-9.528-6.766-17.993-16.293-18.63zm-122.006 465.902v-52.1c0-1.378 1.122-2.5 2.5-2.5h51.9zm94.939-23.757c-.244 1.51-1.131 2.286-2.66 2.327l-46.28-3.096 31.752-31.611c1.414-1.407 2.209-3.32 2.209-5.315v-355.86c0-9.649-7.851-17.5-17.5-17.5h-77.993c-9.697 0-9.697 15 0 15h77.993c1.379 0 2.5 1.122 2.5 2.5v347.712h-62.46c-9.649 0-17.5 7.851-17.5 17.5v62.753h-218.641c-1.378 0-2.5-1.122-2.5-2.5v-425.465c0-1.378 1.122-2.5 2.5-2.5h178.168c9.697 0 9.697-15 0-15h-123.868l2.244-33.556c.244-1.511 1.131-2.286 2.661-2.327l295.44 19.76c1.511.244 2.287 1.131 2.328 2.661z" />
                    <path d="m267.827 237.047h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z" />
                    <path d="m267.827 289.332h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z" />
                    <path d="m55.774 192.262c0 4.142 3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5h-204.553c-4.142 0-7.5 3.358-7.5 7.5z" />
                    <path d="m91.807 139.977c0 4.142 3.358 7.5 7.5 7.5h132.487c4.142 0 7.5-3.358 7.5-7.5s-3.358-7.5-7.5-7.5h-132.487c-4.142 0-7.5 3.358-7.5 7.5z" />
                    <path d="m194.755 438.787c-13.489.036-26.978.065-40.467.086-4.534.007-9.067.013-13.6.016-8.215.006-13.75-1.643-15.59-10.679-1.556-7.64-12.364-6.613-14.464 0-5.19 16.337-13.774 9.936-18.582-1.053-4.797-10.963-6.027-23.233-8.122-34.9-1.54-8.573-14.506-6.17-14.732 1.994-.298 10.751-1.302 21.331-4.031 31.758-2.815 10.758-7.034 21.097-11.222 31.376-3.651 8.961 10.867 12.816 14.464 3.988 3.711-9.108 7.427-18.266 10.193-27.714 5.14 12.36 15.774 26.34 30.927 18.101 2.819-1.533 5.452-3.712 7.763-6.253 7.88 9.106 19.609 8.388 30.584 8.375 15.627-.02 31.254-.054 46.881-.095 9.649-.025 9.667-15.025-.002-15z" />
                    <path d="m505.932 246.439c-3.897-3.878-9.255-5.867-14.695-6.014l-5.668.028v-10.719c0-6.529-3.878-13.427-9.433-16.862v-15.098c0-31.069-48.372-30.934-48.372.146v15.1c-5.659 3.498-9.455 9.741-9.455 16.852v10.982c-24.966 1.7-25.037 39.745.028 41.232.16 33.575.152 66.6-.028 100.737-.049 9.414 14.949 9.966 15 .079.18-34.166.188-67.22.029-100.823l37.211-.185s-.048 110.848-.048 160.784c0 24.338-37.219 24.5-37.219-.253l.013-13.677c.585-9.68-14.387-10.583-14.973-.904v12.834c0 11 3.402 20.316 9.988 26.869.586 15.693 7.198 30.878 18.369 41.956 3.205 3.18 7.642 2.208 10.744-.182 11.365-11.385 17.769-26.394 18.169-42.414 4.951-4.931 9.908-9.896 9.908-26.896l.006-68.351c12.97 3.689 26.494-6.348 26.494-19.946v-90.672c0-5.523-2.155-10.709-6.068-14.603zm-72.623-5.727v-10.841c0-2.219 1.523-4.08 3.573-4.633l30.025-.149c.84.208 1.615.605 2.243 1.231.915.911 1.419 2.123 1.419 3.414v10.794zm18.671-52c4.604 0 9.155 4.514 9.155 9.062v12.166l-18.372.091v-12.111c.001-5.053 4.133-9.183 9.217-9.208zm-.011 303.901c-3.487-4.942-6.009-10.531-7.417-16.406 2.322.503 4.674.765 7.027.765 2.627 0 5.253-.326 7.839-.957-1.374 5.964-3.892 11.587-7.449 16.598zm45.031-140.899c0 7.101-11.452 7.66-11.452.131 0 0 .013-70.974.021-77.48.005-4.196-3.483-7.509-7.558-7.509l-58.389.29c-7.242 0-7.073-11.331.074-11.366l71.615-.355c3.463.295 5.359 2.168 5.688 5.617v90.672z" />
                  </g>
                </g>
              </svg>
            </div>
            <div class="solu_title">
              <h3>Paciente: <%= appointment.patient.name %></h3>
            </div>
            <div class="solu_title">
              <h3>Médico: <%= appointment.physician.name %></h3>
             
            </div>
            <div class="solu_description">
              <p>
                Data e Hora: <%= appointment.appointment_date.strftime(" %m, %b,  %Y - %H:%M") %>
              </p>
              <%= link_to 'Editar Consulta', edit_appointment_path(appointment),  class:"btn btn-primary" %>
              <%= link_to 'Ver consulta', appointment, class:"btn btn-primary" %>
            </div>
          </div>
          
        </div>
        <!--  -->
        
      </div>
    </div>
  </div>


<% end %>


<br>
<br>
<br>
</body>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Appointment date:</strong>
  <%= @appointment.appointment_date %>
</p>

<p>
  <strong>descricao:</strong>
  <%= @appointment.patient.descricao %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="">Nome</label>
    <%= form.text_field :name %>
    <label for="">Email</label>
    <%= form.text_field :email %>
    <label for="">Descrição</label>
    <%= form.text_field :descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<br>
<div class="row">
  <div class="col-xs-6">
    <h3 class="panel-title text-center">Pacientes</h3>
      
    
  </div>
</div>

<hr style="background-color: black
;">


<div class="row text-center" style=" --bs-gutter-x: -15rem;">
<% @patients.each do |patient| %> 
<div class="col-sm-3 text-center">
<div class="container">
<div class="a-box">
  <div class="img-container">
    <div class="img-inner">
      <div class="inner-skew">
        <img src="https://cdn-icons-png.flaticon.com/512/754/754554.png">
      </div>
    </div>
  </div>
  <div class="text-container"> 
    <h3>Paciente: <%= patient.name %></h3>
    <div>
      <h3>Descriçao: <%= patient.descricao %></h3>
    </div>
    <br>
    <td><%= link_to 'Detalhes', patient,  class: 'btn btn-outline-info' %></td>
      <td><%= link_to 'Editar', edit_patient_path(patient), class: 'btn btn-outline-success' %></td>
  </div>
</div>
</div>
</div>

<% end %>

</div>


<br>
<br>
<br>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/physicians/_appointment_fields.html.erb
<div class="card text-white bg-success mb-3 nested-fields" style="max-width: 45rem;">
  <div class="card-header">Consulta</div>
  <div class="card-body">
    <label>Data da Consulta <abbr title="obrigatório">*</abbr></label>
    <%= f.datetime_field :appointment_date, class: 'form-control', required: true %>
    <%= f.fields_for :patient do |appointment_patient| %>
    <label>Nome do Paciente <abbr title="obrigatório">*</abbr></label>
    <%= appointment_patient.text_field :name, autocomplete: "nope" ,class: 'form-control' , placeholder: 'Ex: João Souza Cardoso', required: true %>
    <label>Descrição do Paciente <abbr title="obrigatório">*</abbr></label>
    <%= appointment_patient.text_field :descricao_paciente, autocomplete: "nope" ,class: 'form-control' , placeholder: 'Ex: João Souza Cardoso', required: true %>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <%end%>
    
      <%= link_to_remove_association "remove" , f, class:"btn btn-danger" %>
    
  </div>
</div>

app/views/physicians/_form.html.erb
<%= simple_form_for @physician do |form| %>
  <% if physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row"> 
                 
    <div class="col-md-2">
      <div class="fieldlabels">
        <label>Nome do Médico <abbr title="obrigatório">*</abbr></label>
     <%= form.text_field :name, autocomplete: "nope" ,class: 'form-control' , placeholder: 'Ex: João Souza Cardoso', required: true %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="fieldlabels">
        <label>Tipo de Médico <abbr title="obrigatório">*</abbr></label>
     <%= form.text_field :tipo, autocomplete: "nope" ,class: 'form-control' , placeholder: 'Ex: Dentista', required: true %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="fieldlabels">
        <label>Tipo de Médico <abbr title="obrigatório">*</abbr></label>
     <%= form.text_field :descricao, autocomplete: "nope" ,class: 'form-control' , placeholder: 'Função', required: true %>
      </div>
    </div>

    <div class="col-md-2">
      
  <%= link_to_add_association 'add appointment',form, :appointments,
     'data-association-insertion-node' => "#appointments-patient ol",
    'data-association-insertion-method' => "append", :wrap_object => Proc.
   new {|appointment| appointment.build_patient; appointment }, class:"btn btn-primary"%>
   
   </div>
   <br>
    
 <hr/>

 <fieldset id="appointments-patient">
  <ol>

  </ol>
</fieldset>
  </div>
  

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/physicians/edit.html.erb
<h1>Editing Physician</h1>

<%= render 'form', physician: @physician %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<br>
<div class="row">
  <div class="col-xs-6">
    <h3 class="panel-title text-center">Médicos</h3>
      
    
  </div>
</div>

<hr style="background-color: black
;">
<div class="row row-cols-md-4 ">
  <% @physicians.each do |physician| %>
    <ul>
      <li class="booking-card"
          style="background-image: url(https://img.freepik.com/fotos-gratis/bela-jovem-doutora-olhando-a-camera-no-escritorio_1301-7807.jpg?t=st=1655908257~exp=1655908857~hmac=ced80ca9cb752007fae75f9ad879003ca860cae2e5a0ec762f3ebafa7278b60b&w=740)">
          <div class="book-container">
            <div class="content">
              <%= link_to 'Ver Consultas', physician, class: 'btn btn-primary mt-4' %>
            </div>
          </div>
          
          <div class="informations-container">
            <h2 class="title"><%= physician.name %></h2>
            <p class="sub-title"><%= physician.tipo %></p>      
              </svg><%= physician.descricao %></p>
                <div class="more-information">                
              <p><%= link_to 'Adicionar Consulta', edit_physician_path(physician), class: 'btn btn-outline-success' %> <%= link_to 'Apagar', physician,class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %></p>     
            </div>
          </div>
      </li>
   </ul>
<%end%>
</div>
<br>

app/views/physicians/new.html.erb
<h1>New Physician</h1>

<%= render 'form', physician: @physician %>

<%= link_to 'Back', physicians_path %>